// Code generated by mockery v1.0.0
package mocks

import (
	mock "github.com/stretchr/testify/mock"
	redis "gopkg.in/redis.v5"

	time "time"
)

// redisCommand is an autogenerated mock type for the redisCommand type
type RedisCommand struct {
	mock.Mock
}

// Set provides a mock function with given fields: key, value, expiration
func (_m *RedisCommand) SetSessionData(key string, value interface{}, expiration time.Duration) *redis.StatusCmd {
	ret := _m.Called(key, value, expiration)

	var r0 *redis.StatusCmd
	if rf, ok := ret.Get(0).(func(string, interface{}, time.Duration) *redis.StatusCmd); ok {
		r0 = rf(key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}

	return r0
}

func (_m *RedisCommand) SetRedisClient(*redis.Options) error {
	return nil
}
