// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// SessionHandlerInterface is an autogenerated mock type for the SessionHandlerInterface type
type SessionHandlerInterface struct {
	mock.Mock
}

// EncodeSessionData provides a mock function with given fields:
func (_m *SessionHandlerInterface) EncodeSessionData() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateSession provides a mock function with given fields:
func (_m *SessionHandlerInterface) ValidateSession() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
